const id = {
  greetings: {
    morning: "Selamat Pagi",
    afternoon: "Selamat Siang",
    evening: "Selamat Sore",
    night: "Selamat Malam",
  },
  home: {
    subtitle: "Bagaimana saya dapat membantu anda hari ini?",
    cameraButton: "Kamera",
    scanButton: "Pindai",
    voiceButton: "Suara",
    helpButton: "Bantuan",
    settingsButton: "Pengaturan",
    emergencyButton: "Panggilan Darurat",
  },
  permissions: {
    camera: "Kami butuh izin Anda untuk menggunakan kamera",
    microphone: "Kami butuh izin Anda untuk menggunakan mikrofon",
    gallery: "Anda perlu memberikan izin galeri untuk menggunakan fitur ini.",
    grantPermission: "Berikan Izin",
    cameraDenied: "Izin kamera dinonaktifkan. Aktifkan melalui pengaturan ponsel.",
    microphoneDenied: "Izin mikrofon dinonaktifkan. Aktifkan melalui pengaturan ponsel.",
  },
  cameraScreen: {
    processing: "Memproses...",
    ready: "Siap",
    done: "Selesai",
    objectInFront: (objectName: string) => `Di depan ada ${objectName}`,
  },
  scanScreen: {
    title: "Scan Dokumen",
    placeholder: "Pilih metode pemindaian",
    camera: "Kamera",
    upload: "Unggah",
    processing: "Sedang memproses...",
  },
  scanResult: {
    title: "Hasil Pindai",
    noTextDetected: "Tidak ada teks yang terdeteksi.",
    listen: "Dengarkan",
    stop: "Berhenti",
    imageProcessing: "Memproses gambar...",
    scannerOpening: "Membuka pemindai...",
    imageProcessingFailed: "Gagal memproses gambar, silakan coba lagi.",
    imageTakenProcessing: "Gambar diambil, sedang memproses",
  },
  voiceScreen: {
    title: "Suara",
    infoProcessing: "Mengubah suara menjadi teks...",
    infoListening: "Sedang mendengarkan...",
    infoDefault: "Tekan tombol untuk berbicara",
    recordingFailed:
      "Gagal memulai rekaman. Pastikan izin mikrofon telah diberikan.",
  },
  voiceResult: {
    title: "Hasil Suara",
  },
  settings: {
    title: "Pengaturan",
    theme: "Tema",
    darkMode: "Mode Gelap",
    language: "Bahasa",
    helpAndGuide: "Panduan & Bantuan",
    privacyAndSecurity: "Privasi & Keamanan",
    about: "Tentang Aplikasi",
    appName: "TemanDifa",
  },
  general: {
    back: "Kembali",
    error: "Error",
    failure: "Gagal",
    networkError: "Gagal terhubung ke server. Periksa koneksi internet Anda.",
    genericError: "Terjadi kesalahan. Silakan coba lagi nanti.",
    serverError: "Terjadi kesalahan pada server.",
  },
};

const en: typeof id = {
  greetings: {
    morning: "Good Morning",
    afternoon: "Good Afternoon",
    evening: "Good Evening",
    night: "Good Night",
  },
  home: {
    subtitle: "How can I help you today?",
    cameraButton: "Camera",
    scanButton: "Scan",
    voiceButton: "Voice",
    helpButton: "Help",
    settingsButton: "Settings",
    emergencyButton: "Emergency Call",
  },
  permissions: {
    camera: "We need your permission to use the camera",
    microphone: "We need your permission to use the microphone",
    gallery: "You need to grant gallery permissions to use this feature.",
    grantPermission: "Grant Permission",
    cameraDenied: "Camera permission is disabled. Please enable it in the phone settings.",
    microphoneDenied: "Microphone permission is disabled. Please enable it in the phone settings.",
  },
  cameraScreen: {
    processing: "Processing...",
    ready: "Ready",
    done: "Done",
    objectInFront: (objectName: string) => `In front is ${objectName}`,
  },
  scanScreen: {
    title: "Scan Document",
    placeholder: "Select a scanning method",
    camera: "Camera",
    upload: "Upload",
    processing: "Processing...",
  },
  scanResult: {
    title: "Scan Result",
    noTextDetected: "No text detected.",
    listen: "Listen",
    stop: "Stop",
    imageProcessing: "Processing image...",
    scannerOpening: "Opening scanner...",
    imageProcessingFailed: "Failed to process image, please try again.",
    imageTakenProcessing: "Image taken, processing",
  },
  voiceScreen: {
    title: "Voice",
    infoProcessing: "Converting voice to text...",
    infoListening: "Listening...",
    infoDefault: "Press the button to speak",
    recordingFailed:
      "Failed to start recording. Make sure microphone permission is granted.",
  },
  voiceResult: {
    title: "Voice Result",
  },
  settings: {
    title: "Settings",
    theme: "Theme",
    darkMode: "Dark Mode",
    language: "Language",
    helpAndGuide: "Help & Guide",
    privacyAndSecurity: "Privacy & Security",
    about: "About App",
    appName: "TemanDifa",
  },
  general: {
    back: "Back",
    error: "Error",
    failure: "Failed",
    networkError: "Failed to connect to the server. Check your internet connection.",
    genericError: "An error occurred. Please try again later.",
    serverError: "An error occurred on the server.",
  },
};

export const Strings = { id, en };